In [1]:
import pandas as pd
import numpy as np

In [11]:
vector = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(vector)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [15]:
print(vector.shape)
print(vector[0,1])

(3, 3)
2


.shape para conocer las dimesiones de la matriz
.reshape podemos redimensionar una matriz. Una de 3x3 puede pasar a ser de una dimension de 9 indices.

In [23]:
numeros = np.array([1,2,3,4,5,6,7,8])
print(numeros.shape)
print(numeros)

numeros2 = numeros.reshape((2,4))
print(numeros2.shape)
print(numeros2)

(8,)
[1 2 3 4 5 6 7 8]
(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [3]:
df = pd.read_csv('marathon_results_2017.csv')

In [4]:
print(df)

       Unnamed: 0    Bib                      Name  Age M/F              City  \
0               0     11           Kirui, Geoffrey   24   M          Keringet   
1               1     17               Rupp, Galen   30   M          Portland   
2               2     23             Osako, Suguru   25   M      Machida-City   
3               3     21          Biwott, Shadrack   32   M     Mammoth Lakes   
4               4      9            Chebet, Wilson   31   M          Marakwet   
5               5     15          Abdirahman, Abdi   40   M           Phoenix   
6               6     63        Maiyo, Augustus K.   33   M  Colorado Springs   
7               7      7               Sefir, Dino   28   M       Addis Ababa   
8               8     18            Puskedra, Luke   27   M            Eugene   
9               9     20               Ward, Jared   28   M         Kaysville   
10             10     22             Quigley, Sean   32   M         Braintree   
11             11      6    